name: Generate Isometric Commit Calendar

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: # Возможность запустить вручную

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Генерация полугодового календаря
      - name: Generate Half-Year Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes

      # Шаг 3: Генерация полного календаря за год
      - name: Generate Full-Year Isometric Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
